dist: trusty
language: java
sudo: false
jdk:
  - oraclejdk8
  - openjdk8
before_install:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"

script:
 - mvn install -B -V
 - mvn javadoc:jar
 - mvn javadoc:test-aggregate
 - mvn cobertura:cobertura
 - mvn site

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    secure: CCjvzkv9khqeAIgbMjXnIoQi0qZ55K6RtxGk9bqzY+r/xiUTmgat9N9+Alyuq3kK9rNNoQZQwR9rOyvPf9ymkifFnGxSglBSLHXzpxnftwOCasB0wf0OkENYfa8BrDhSk9EZPHsfGNqtcb5tm6/hLK2Kd49qGkYkT1ct3O0jWwWsn0SOmyNh2znIxMwCGKUMmrk/opVEKLvXmZRM7jCStCzFRrfR/d0QrPa9MYOLaFy75bVK8NcIJd4s6seOMf9OifBnfE34FY9DOL8fWnZEIx9eG6ajMYDP+6gn/v9JOZoNybfTojrpsWqCK1ytItzeToMAz9n8ULB0sUXAY0zk5u1VMaWQa9w/769hwATkNv49GI/MLM2apJY2HaBvzPizWIrVpR89uilM+pxUaH51D94cnWjtVLaSt7BMJ1K/dy2hpEaBElmG0iWYsqpdpKTJkVCDOYxs8sumEFsvIUWcQkiuk5EKrxfAjqcUpf5yTvkhFtkiIU2oxf2sGXXVFGocM+dpzbFXlhmk76caeRD+tw9bNfDAbuy7JjEfVS7ls3gmUHu3298JZhfiR89YxBx7BDZ7Kr9vurdXaYihoCqkXykw8D7MiZGRcdMJbGmRGmsILho9KtlJJsP7BNG6W3uA/z5gRzlV3RJVjXigWDCpOUxp+TVNP9ug4ymmSf2g6cQ=
