language: java
sudo: false
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
before_install:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"

script:
 - mvn clean install
 - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
