name: Python Formatter (isort & black)

on:
  pull_request:
    branches: [master]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install isort and black
        run: |
          python -m pip install --upgrade pip
          pip install isort black
      - name: Run isort and black
        run: |
          isort -c -l 88 -m 3 -tc src/main/python/aut/*
          black --check -q src/main/python/aut/*
