name: Run scalafmt

on:
  push:
    branches:
      - master

jobs:
  scalafmt-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Running scalafmt
        uses: openlawteam/scalafmt-ci@v2
